import {
  lucideActivity,
  lucideArchive,
  lucideArrowLeft,
  lucideArrowRight,
  lucideArrowUp,
  lucideArrowUpRight,
  lucideBadgeCheck,
  lucideBan,
  lucideBell,
  lucideBold,
  lucideBookOpen,
  lucideBookOpenText,
  lucideCalendar,
  lucideCalendarPlus,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsUpDown,
  lucideChevronUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleDollarSign,
  lucideCircleX,
  lucideClipboard,
  lucideClock,
  lucideCode,
  lucideCodeXml,
  lucideCopy,
  lucideCreditCard,
  lucideDollarSign,
  lucideEllipsis,
  lucideEye,
  lucideFile,
  lucideFileText,
  lucideFolder,
  lucideFolderOpen,
  lucideFolderPlus,
  lucideHeart,
  lucideHouse,
  lucideInbox,
  lucideInfo,
  lucideItalic,
  lucideLayers,
  lucideLayers2,
  lucideLayoutDashboard,
  lucideLightbulb,
  lucideLightbulbOff,
  lucideListFilterPlus,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMail,
  lucideMinus,
  lucideMonitor,
  lucideMoon,
  lucideMoveRight,
  lucidePalette,
  lucidePanelLeft,
  lucidePlus,
  lucidePopcorn,
  lucidePuzzle,
  lucideSave,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideSmartphone,
  lucideSparkles,
  lucideSquare,
  lucideSquareLibrary,
  lucideStar,
  lucideSun,
  lucideSunMoon,
  lucideTablet,
  lucideTag,
  lucideTerminal,
  lucideTextAlignCenter,
  lucideTextAlignEnd,
  lucideTextAlignStart,
  lucideTrash2,
  lucideUnderline,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideX,
  lucideZap,
} from '@ng-icons/lucide';

export const ZARD_ICON_IMPORTS = {
  lucideActivity,
  lucideArchive,
  lucideArrowLeft,
  lucideArrowRight,
  lucideArrowUp,
  lucideArrowUpRight,
  lucideBadgeCheck,
  lucideBan,
  lucideBell,
  lucideBold,
  lucideBookOpen,
  lucideBookOpenText,
  lucideCalendar,
  lucideCalendarPlus,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsUpDown,
  lucideChevronUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleDollarSign,
  lucideCircleX,
  lucideClipboard,
  lucideClock,
  lucideCode,
  lucideCodeXml,
  lucideCopy,
  lucideCreditCard,
  lucideDollarSign,
  lucideEllipsis,
  lucideEye,
  lucideFile,
  lucideFileText,
  lucideFolder,
  lucideFolderOpen,
  lucideFolderPlus,
  lucideHeart,
  lucideHouse,
  lucideInbox,
  lucideInfo,
  lucideItalic,
  lucideLayers,
  lucideLayers2,
  lucideLayoutDashboard,
  lucideLightbulb,
  lucideLightbulbOff,
  lucideListFilterPlus,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMail,
  lucideMinus,
  lucideMonitor,
  lucideMoon,
  lucideMoveRight,
  lucidePalette,
  lucidePanelLeft,
  lucidePlus,
  lucidePopcorn,
  lucidePuzzle,
  lucideSave,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideSmartphone,
  lucideSparkles,
  lucideSquare,
  lucideSquareLibrary,
  lucideStar,
  lucideSun,
  lucideSunMoon,
  lucideTablet,
  lucideTag,
  lucideTerminal,
  lucideTextAlignCenter,
  lucideTextAlignEnd,
  lucideTextAlignStart,
  lucideTrash2,
  lucideUnderline,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideX,
  lucideZap,
};

export const ZARD_ICONS = {
  house: 'lucideHouse',
  settings: 'lucideSettings',
  user: 'lucideUser',
  search: 'lucideSearch',
  bell: 'lucideBell',
  mail: 'lucideMail',
  calendar: 'lucideCalendar',
  'log-out': 'lucideLogOut',
  'panel-left': 'lucidePanelLeft',
  bold: 'lucideBold',
  inbox: 'lucideInbox',
  italic: 'lucideItalic',
  underline: 'lucideUnderline',
  'text-align-center': 'lucideTextAlignCenter',
  'text-align-end': 'lucideTextAlignEnd',
  'text-align-start': 'lucideTextAlignStart',
  check: 'lucideCheck',
  x: 'lucideX',
  info: 'lucideInfo',
  'triangle-alert': 'lucideCircle',
  circle: 'lucideCircle',
  'circle-alert': 'lucideCircleAlert',
  'circle-check': 'lucideCircleCheck',
  'circle-x': 'lucideCircleX',
  'circle-dollar-sign': 'lucideCircleDollarSign',
  'circle-small': 'lucideCircle',
  ban: 'lucideBan',
  'chevron-down': 'lucideChevronDown',
  'chevron-up': 'lucideChevronUp',
  'chevron-left': 'lucideChevronLeft',
  'chevron-right': 'lucideChevronRight',
  'chevrons-up-down': 'lucideChevronsUpDown',
  'move-right': 'lucideMoveRight',
  'arrow-right': 'lucideArrowRight',
  'arrow-up': 'lucideArrowUp',
  'arrow-up-right': 'lucideArrowUpRight',
  folder: 'lucideFolder',
  'folder-open': 'lucideFolderOpen',
  'folder-plus': 'lucideFolderPlus',
  file: 'lucideFile',
  'file-text': 'lucideFileText',
  'layout-dashboard': 'lucideLayoutDashboard',
  'loader-circle': 'lucideLoaderCircle',
  save: 'lucideSave',
  copy: 'lucideCopy',
  eye: 'lucideEye',
  ellipsis: 'lucideEllipsis',
  terminal: 'lucideTerminal',
  clipboard: 'lucideClipboard',
  moon: 'lucideMoon',
  sun: 'lucideSun',
  lightbulb: 'lucideLightbulb',
  'lightbulb-off': 'lucideLightbulbOff',
  palette: 'lucidePalette',
  sparkles: 'lucideSparkles',
  heart: 'lucideHeart',
  star: 'lucideStar',
  zap: 'lucideZap',
  popcorn: 'lucidePopcorn',
  shield: 'lucideShield',
  puzzle: 'lucidePuzzle',
  layers: 'lucideLayers',
  'layers-2': 'lucideLayers2',
  'square-library': 'lucideSquareLibrary',
  code: 'lucideCode',
  'code-xml': 'lucideCodeXml',
  'book-open': 'lucideBookOpen',
  'book-open-text': 'lucideBookOpenText',
  users: 'lucideUsers',
  monitor: 'lucideMonitor',
  smartphone: 'lucideSmartphone',
  tablet: 'lucideTablet',
  'badge-check': 'lucideBadgeCheck',
  'folder-code': 'lucideFolderCode',
  plus: 'lucidePlus',
  minus: 'lucideMinus',
  'arrow-left': 'lucideArrowLeft',
  archive: 'lucideArchive',
  clock: 'lucideClock',
  'calendar-plus': 'lucideCalendarPlus',
  'list-filter-plus': 'lucideListFilterPlus',
  trash: 'lucideTrash2',
  tag: 'lucideTag',
  'sun-moon': 'lucideSunMoon',
  'dark-mode': 'lucideCircle',
  square: 'lucideSquare',
  'dollar-sign': 'lucideDollarSign',
  'user-plus': 'lucideUserPlus',
  'credit-card': 'lucideCreditCard',
  activity: 'lucideActivity',
} as const;

export type ZardIcon = keyof typeof ZARD_ICONS;
